### ISSUE TITLE
Port 5959 should not be open

### ISSUE THREAD

**Issue by a1ecbr0wn** [chimbosonic/veilid-container#1]
It is unencrypted and should not be exposed:

https://discord.com/channels/1077244355439509565/1130865892947935374/1142699073250537522

**Comment by chimbosonic** [comment]
Hi @a1ecbr0wn,
As described in the README.md I explicitly stated that it's the api port. 
Having it as a 'EXPOSE' command only tells you it's a valid port, it does not publish it. The user of the container doesn't need to expose it if they don't want to. I am purely documenting that there is a service on that port. I could update the README.md file to reflect the dangers of publishing the port.

**Comment by a1ecbr0wn** [comment]
fair enough

**Comment by chimbosonic** [comment]
I updated the `README.md` file to have  a warning.
